server:
  port: 9411
spring:
  application:
    name: zipkin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
  instance:
    instance-id: zipkin-server
  #  prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
