version: "3"

services:
  eureka-server-demo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "registry-vpc.cn-beijing.aliyuncs.com/alauda-cloud/eureka-server"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xmx480m
      - APP_NAME=eureka-server-demo
    labels:
      aliyun.logs.cms-service: "stdout"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=cloud.linkme.org.cn
        - com.df.port=8761
        - com.df.srcPort=8079
networks:
  default:
    external:
      name: linkme