server:
  port: 10000

spring:
  application:
      name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring:
#  profiles: default1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:8762/eureka/
#server:
#  port: 8761
#---
#spring:
#  profiles: default2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:8761/eureka/
#server:
#  port: 8762
#---
#spring:
#  profiles: eureka1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${security.user.name}:${security.user.password}@eureka2:${server.port}/eureka/
#---
#spring:
#  profiles: eureka2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${security.user.name}:${security.user.password}@eureka1:${server.port}/eureka/
