
server:
  port: 10009
swagger:
  service-name: "Spring Cloud Demo API Docs"
  service-desc: "DEMO接口文档"
spring:
 # profiles.include:
  #  - redis
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

