server:
  port: 10001
spring:
  application:
    name: config-server
  zipkin:  #链路追踪
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yan981471305/spring-cloud.git
          ignore-local-ssh-settings: true
          strictHostKeyChecking: false
          force-pull: true
          search-paths: config
          clone-on-start: true
          username: yan981471305
          password: yan199436

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
  instance:
    instance-id: config-server
  #  prefer-ip-address: true

